//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServeEaseV3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public int transaction_id { get; set; }
        public Nullable<int> payment_id { get; set; }
        public Nullable<int> apt_id { get; set; }
        public System.DateTime tx_date { get; set; }
        public Nullable<int> payment_token_id { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string tx_status { get; set; }
    
        public virtual appointment appointment { get; set; }
        public virtual payment_details payment_details { get; set; }
    }
}
